// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fighters/{id}": {
            "get": {
                "description": "responds with single fighter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Gets Fighter by ID (Public/Static).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get fighter by id",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Fighter"
                        }
                    }
                }
            }
        },
        "/my/fighters": {
            "get": {
                "description": "responds with all the users fighters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Gets Fighters by UserID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.Fighter"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "responds with ` + "`" + `pong` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Ensure the API is working/listening",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.pong"
                        }
                    }
                }
            }
        },
        "/units": {
            "get": {
                "description": "responds with all available single unit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Gets Unit by ID (Public/Static).",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.Unit"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "responds with the newly created unit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Unit (Administrative)",
                "parameters": [
                    {
                        "description": "new unit",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.Unit"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "newly created unit",
                        "schema": {
                            "$ref": "#/definitions/app.Unit"
                        }
                    }
                }
            }
        },
        "/units/{id}": {
            "get": {
                "description": "responds with single unit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Gets Unit by ID (Public/Static).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get unit by id",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Unit"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.Fighter": {
            "type": "object",
            "properties": {
                "base_unit": {
                    "$ref": "#/definitions/app.Unit"
                },
                "id": {
                    "type": "string"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.Move"
                    }
                },
                "stats": {
                    "description": "calculated at level up",
                    "$ref": "#/definitions/app.StatGroup"
                },
                "string": {
                    "type": "integer"
                },
                "unit_id": {
                    "description": "for hydration",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "app.Move": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "element": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "metas": {
                    "description": "this is tricky, more a demo than anything",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.MoveMeta"
                    }
                },
                "name": {
                    "type": "string"
                },
                "rest_duration": {
                    "type": "integer"
                }
            }
        },
        "app.MoveMeta": {
            "type": "object"
        },
        "app.StatGroup": {
            "type": "object",
            "properties": {
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "health": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                }
            }
        },
        "app.Unit": {
            "type": "object",
            "properties": {
                "element": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/app.StatGroup"
                },
                "unit_type": {
                    "description": "because ` + "`" + `type` + "`" + ` is a reserved word",
                    "type": "integer"
                }
            }
        },
        "handlers.pong": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Gacha Game: Monolith",
	Description: "Proof of Concept, inmemory Gacha Game",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
