basePath: /api/v1
definitions:
  app.Unit:
    properties:
      element:
        type: integer
      id:
        type: string
      name:
        type: string
      unit_type:
        description: because type is a reserved word
        type: integer
    type: object
  handlers.pong:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Proof of Concept, inmemory Gacha Game
  title: 'Gacha Game: Monolith'
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: responds with `pong`
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.pong'
      summary: Ensure the API is working/listening
  /static/units:
    get:
      consumes:
      - application/json
      description: responds with all available single unit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/app.Unit'
            type: array
      summary: Gets Unit by ID (Public/Static).
  /static/units/{id}:
    get:
      consumes:
      - application/json
      description: responds with single unit
      parameters:
      - description: get unit by id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Unit'
      summary: Gets Unit by ID (Public/Static).
swagger: "2.0"
