# in order for this to work, install rust plugin for protoc

# ensure rust is installed, and cargo is in your path
# cargo install protobuf-codegen

gen:
	protoc --rust_out=./dist/rust --go_out=./dist/go  ./src/*